# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


## "uri": "mysql://b2707ee0c378d6:c6073a43@us-cdbr-iron-east-04.cleardb.net:3306/ad_01c858d36d7ea94?reconnect=true"

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: db1
  username: rails
  password: Ruby0nRails
  host: ec2-54-89-100-93.compute-1.amazonaws.com
  port: 3306 

