# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

<%

database_url = "postgres://admin:ZEFBMASLWKOZEHAR@bluemix-sandbox-dal-9-portal.4.dblayer.com:21697/compose"

%>

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  url: <%= database_url %>


